name: Armbian OS Image request
description: Suggest image release combination that currently does not exist on download pages
title: "Please ..."
labels: ["feature"]
assignees: "igorpecovnik"
body:
  - type: textarea
    id: image
    attributes:
      label: "Which variant would you like us to enable?"
      description: "[Supported and WIP images only from here](https://github.com/armbian/build/tree/main/config/boards)"
      placeholder: Tell us what is missing!
      value: "BOARD: bananapim3, BRANCH: current"
    validations:
      required: true
